import type {Metadata} from "next";
import Image from "next/image";
import {PageShell} from "@/components/PageShell";
import {business} from "@/data/business";
import {Arrow} from "@/components/Icons";

export const metadata:Metadata={title:"Về Tamas",description:"Tamas chuẩn bị những bó hoa theo câu chuyện, tone màu và ngân sách của người tặng.",alternates:{canonical:"/ve-tamas"}};

const aboutImages={hero:"/images/enhanced/01_Fresh-Flowers/tamas-fresh-pastel-bouquet-04.webp",opening:"/images/enhanced/01_Fresh-Flowers/tamas-fresh-pastel-bouquet-01.webp",listening:"/images/enhanced/01_Fresh-Flowers/tamas-fresh-pastel-bouquet-03.webp",finishing:"/images/enhanced/02_Wax-Flowers/tamas-wax-flower-price-grid-01.webp",closing:"/images/enhanced/05_Flower-Box/tamas-flower-box-heart-red-01.webp"};

export default function About(){return <PageShell>
<section className="about-editorial-hero"><div className="about-editorial-copy"><p className="location">Về Tamas</p><h1>Hoa được chuẩn bị<br/>để người nhận nhớ mãi<br/>khoảnh khắc mở quà.</h1><p>Một bó hoa không chỉ để đẹp trong vài giờ. Nó là cách một người gọi tên sự quan tâm của mình, bằng màu sắc, mùi hương và những điều đôi khi rất khó nói thành lời.</p></div><div className="about-hero-collage" aria-label="Những bó hoa pastel do Tamas chuẩn bị"><div className="about-hero-primary"><Image src={aboutImages.hero} alt="Bó hoa pastel do Tamas chuẩn bị" fill sizes="(max-width: 800px) 100vw, 42vw" priority/></div><div className="about-hero-secondary"><Image src={aboutImages.opening} alt="Chi tiết hoa pastel tại Tamas" fill sizes="(max-width: 800px) 44vw, 20vw"/></div></div></section>
<main className="about-story-page"><section className="about-chapter about-chapter-opening" id="khoi-dau"><div><h2>Mọi chuyện bắt đầu từ người sẽ nhận hoa.</h2><p>Trước khi nghĩ đến một mẫu hoa, Tamas thường nghĩ về khoảnh khắc ở đầu bên kia món quà. Có thể đó là một buổi sáng sinh nhật vội vàng, một cuộc gặp sau nhiều ngày xa cách, một lời cảm ơn chưa từng nói, hay đơn giản là mong ai đó thấy ngày hôm nay dịu lại một chút. Mỗi dịp mang một nhịp riêng; vì thế, một bó hoa đẹp không nên chỉ là bó hoa giống hệt ảnh mẫu.</p><p>Chúng mình xem ảnh tham khảo như điểm bắt đầu. Điều quan trọng hơn là câu chuyện bạn muốn gửi: người nhận thích những màu yên tĩnh hay rực rỡ, họ là người nhẹ nhàng hay thích điều bất ngờ, món quà cần nhỏ xinh để cầm trên tay hay đủ đầy để lấp đầy một góc phòng. Những chi tiết ấy khiến một thiết kế trở nên gần gũi, thay vì chỉ “đúng kiểu”.</p><p>Vì vậy Tamas không cố tạo ra thật nhiều lựa chọn để bạn phải phân vân. Shop muốn giúp bạn tìm ra một hướng có chủ đích. Có khi đó là một bó hoa hồng phấn với giấy gói trong veo. Có khi là tone trắng xanh thanh thoát cho một lời chúc mừng. Cũng có khi, điều bạn cần nhất chỉ là một gợi ý thật chân thành để bắt đầu cuộc trò chuyện.</p><p>Điều này đặc biệt hữu ích khi bạn đang tặng hoa cho một người mình hiểu nhưng chưa biết diễn đạt thế nào. Bạn không cần biến cảm xúc thành một bảng yêu cầu thật chi tiết. Một kỷ niệm nhỏ, màu áo người ấy thường mặc, một quán cà phê hai người hay đến, hoặc cảm giác bạn muốn họ có khi mở quà đều có thể là gợi ý. Tamas sẽ dùng chúng như những nốt đầu tiên để tìm ra tổng thể phù hợp — vừa đủ cá nhân, vừa đủ tinh tế để người nhận tự cảm được sự quan tâm trong đó.</p></div><figure className="about-image about-image-tall"><Image src={aboutImages.opening} alt="Bó hoa tươi pastel được gói chỉn chu" fill sizes="(max-width: 800px) 100vw, 36vw"/><figcaption>Những sắc độ được chọn để ở cạnh nhau thật tự nhiên.</figcaption></figure></section>
<section className="about-chapter about-chapter-listening" id="lang-nghe"><figure className="about-image about-image-wide"><Image src={aboutImages.listening} alt="Hoa tươi nhiều sắc độ tại Tamas" fill sizes="(max-width: 800px) 100vw, 52vw"/></figure><div><h2>Lắng nghe trước khi chọn hoa.</h2><p>Khi nhắn cho Tamas, bạn không cần biết tên từng loại hoa hay phải có sẵn một ý tưởng hoàn chỉnh. Chỉ cần kể một vài điều: dịp tặng là gì, người nhận là ai, bạn thích tone nào, cần nhận hoa vào lúc nào và ngân sách bạn thấy thoải mái. Từ đó, shop có thể cùng bạn thu hẹp lựa chọn và tìm một thiết kế phù hợp hơn.</p><p>Đó cũng là lý do chúng mình luôn trân trọng những câu nói rất đời thường: “bạn ấy thích màu hồng nhưng không quá ngọt”, “mẹ thích hoa đơn giản”, hay “mình muốn bó hoa nhìn vui một chút”. Những câu ngắn ấy đủ để mở ra cảm xúc cho một thiết kế. Hoa không cần phô trương để gây ấn tượng; đôi khi sự đúng đắn nằm trong một nhành phụ nhẹ, một khoảng giấy gói thoáng, hoặc một màu hoa xuất hiện vừa đủ.</p><p>Sự tư vấn của Tamas không nhằm thay bạn quyết định. Nó là một cách cùng bạn nhìn rõ điều mình muốn gửi đi. Khi đã có hướng, việc chọn hoa trở nên bình tĩnh hơn: bạn hiểu vì sao tone này hợp với người ấy, vì sao bó này cần thêm độ rủ, hay vì sao một flower box sẽ phù hợp với không gian hơn một bó hoa cầm tay.</p><p>Không có một công thức đúng cho mọi lần tặng hoa. Một bó dành cho lễ tốt nghiệp có thể vui và sáng, nhưng không cần phải ồn ào. Một bó cho ngày kỷ niệm có thể trầm hơn, nhưng không nhất thiết chỉ có đỏ hoặc hồng. Tamas thích những khoảng chuyển sắc mềm và những lựa chọn khiến người nhận thấy mình được nhìn thấy. Vì vậy, nếu có điều gì bạn còn lưỡng lự, cứ nói ra; đôi khi chính điểm chưa chắc chắn ấy lại là chìa khoá để tìm thấy hướng đúng.</p></div></section>
<section className="about-pause"><p>“Một bó hoa chỉ thật sự hoàn thành khi người tặng thấy: đúng rồi, đây là điều mình muốn gửi.”</p></section>
<section className="about-chapter about-chapter-making" id="chuan-bi"><div><h2>Chuẩn bị bằng sự chỉn chu của một món quà.</h2><p>Sau khi có hướng, Tamas để ý đến cách những thành phần đứng cạnh nhau. Sắc hoa, lá phụ, lớp giấy gói, ribbon và dáng bó đều góp phần tạo nên cảm giác cuối cùng. Có mẫu cần tròn đầy và mềm; có mẫu lại đẹp hơn khi để một vài nhành vươn ra tự nhiên. Những quyết định ấy nhỏ, nhưng chính chúng tạo nên khoảng thở cho bó hoa và khiến người nhận muốn ngắm lâu hơn một chút.</p><p>Hoa tươi, hoa sáp, hoa len, flower box hay hoa cưới đều có ngôn ngữ riêng. Với hoa tươi, cảm giác mùa và độ mở của bông luôn quan trọng. Với hoa sáp, sự bền màu cần đi cùng vẻ mềm mại để món quà không bị cứng. Với hoa len và gấu bông, tỷ lệ là điều quyết định: đủ đáng yêu nhưng vẫn giữ được sự tinh tế của một món quà. Còn với flower box, Tamas quan tâm đến khoảnh khắc mở nắp — lớp hoa hiện ra cần đủ đầy mà vẫn có điểm để mắt dừng lại.</p><p>Chúng mình không xem sự chăm chút là phần “thêm vào”. Nó là điều cơ bản. Một bó hoa được nâng niu từ lúc chọn tone đến khi buộc ribbon sẽ giúp người tặng tự tin hơn khi trao quà. Và khi món quà đi cùng một lời nhắn, một lời xin lỗi, một lời cảm ơn hay một lời chúc mới bắt đầu, sự chỉn chu ấy sẽ âm thầm làm câu chuyện trọn vẹn hơn.</p></div><div className="about-image-cluster" aria-label="Những kiểu hoa được Tamas chuẩn bị"><figure className="about-image about-image-cluster-main"><Image src={aboutImages.finishing} alt="Bó hoa sáp hồng được Tamas chuẩn bị" fill sizes="(max-width: 800px) 78vw, 31vw"/></figure><figure className="about-image about-image-cluster-accent"><Image src={aboutImages.closing} alt="Flower box hồng tại Tamas" fill sizes="(max-width: 800px) 42vw, 17vw"/></figure></div></section>
<section className="about-closing" id="gap-tamas"><div className="about-closing-image"><Image src={aboutImages.closing} alt="Flower box hồng như một món quà của Tamas" fill sizes="100vw"/></div><div><h2>Ghé Tamas, hoặc bắt đầu bằng một tin nhắn.</h2><p>Dù bạn đã có mẫu hoa yêu thích hay chỉ mới có một cảm giác mơ hồ, Tamas vẫn ở đây để cùng bạn bắt đầu. Hãy gửi shop một bức ảnh, vài màu bạn thích, hoặc chỉ một câu về người nhận. Từ những mẩu thông tin nhỏ đó, chúng mình sẽ gợi ý một thiết kế vừa với dịp tặng và ngân sách của bạn.</p><p>Hoa có thể không nói thay tất cả, nhưng nó mở đầu cho nhiều điều đẹp đẽ: một cuộc gặp, một lời cảm ơn, một lần làm hoà, một dấu mốc mới. Tamas mong mỗi bó hoa khi rời khỏi shop đều giữ được cảm giác ấy — không quá xa cách, không quá cầu kỳ, chỉ thật lòng và được chuẩn bị riêng cho người sẽ nhận.</p><p>Nếu bạn đang ở gần Tamas, bạn cũng có thể ghé shop và để cảm xúc dẫn đường. Có những sắc hoa nhìn trên màn hình rất đẹp nhưng khi đứng cạnh nhau lại kể một câu chuyện khác; có những lớp giấy gói phải chạm vào mới thấy được độ mềm và ánh sáng của chúng. Một cuộc trao đổi ngắn tại shop, hay một cuộc trò chuyện qua tin nhắn, đều có thể bắt đầu từ cùng một điều: bạn muốn ai đó vui hơn vì món quà này. Tamas sẽ cùng bạn đi từ ý tưởng ấy đến một bó hoa đã sẵn sàng để trao.</p><p>Và nếu hôm nay không có một dịp đặc biệt nào cả, hoa vẫn có thể là một lý do rất đẹp. Một bình hoa nhỏ trên bàn làm việc, một nhành hoa mang về sau giờ tan ca, hay một bó hoa dành cho chính mình cũng là cách ghi nhận những ngày đang diễn ra. Tamas tin rằng những điều dịu dàng không cần chờ đến một cột mốc mới được xuất hiện. Đôi khi, chỉ cần một màu hoa mình yêu đã đủ để ngày thường trở nên đáng nhớ hơn.</p><a className="button button-ink" href={business.facebook} target="_blank" rel="noopener noreferrer">Đặt qua fanpage <Arrow/></a></div></section></main>
</PageShell>}
