import type {Metadata} from "next"; import Image from "next/image"; import Link from "next/link"; import {PageShell} from "@/components/PageShell"; import {Arrow} from "@/components/Icons"; import {business} from "@/data/business"; import {ProductCard} from "@/components/ProductCard"; import {getHomePageContent} from "@/sanity/products";
export const metadata:Metadata={alternates:{canonical:"/"}};
export const revalidate = 3600;
export default async function Home(){const {categoryTiles,featuredProducts,instagramImages}=await getHomePageContent(); return <PageShell><section className="hero"><div className="hero-copy"><p className="location">Được chuẩn bị tại Sài Gòn</p><h1>Hoa dành cho những điều khó nói thành lời.</h1><p>Tamas lắng nghe dịp tặng, sắc hoa bạn yêu và câu chuyện bạn muốn gửi đi — rồi chuẩn bị <span className="keep-together">một bó hoa thật riêng.</span></p><div className="hero-actions"><Link className="button button-ink" href="/san-pham">Khám phá hoa <Arrow/></Link><a className="text-link" href={business.facebook} target="_blank" rel="noopener noreferrer">Đặt qua fanpage</a></div></div><div className="hero-image hero-image-portrait" role="img" aria-label="Cô gái ôm bó hoa hồng tại Tamas Flower Store"/><div className="hero-note">Tamas<br/>Flower<br/>Store</div></section>
<section className="section category-section"><div className="section-heading"><h2>Chọn hoa theo cách của bạn.</h2><Link className="text-link" href="/san-pham">Xem tất cả <Arrow/></Link></div><div className="categories">{categoryTiles.map((c,i)=><Link href={`/danh-muc/${c.slug}`} className={`category c${i+1}`} key={c.slug}><Image src={c.image} alt={c.alt} fill sizes="(max-width: 720px) 70vw, 28vw"/><span>{c.name}<Arrow/></span></Link>)}</div></section>
<section className="section featured"><div className="section-heading"><div><h2>Được yêu thích tại Tamas</h2><p>Ba mẫu được khách tìm nhiều — có thể điều chỉnh theo tone và ngân sách của bạn.</p></div><Link className="text-link" href="/san-pham">Xem catalog <Arrow/></Link></div><div className="products-editorial">{featuredProducts.slice(0,3).map(p=><ProductCard product={p} key={p.slug}/>)}</div></section>
<section className="occasions"><div><h2><span className="keep-together">Luôn có một lý do</span><br/><span className="keep-together">để tặng hoa.</span></h2><p>Chọn dịp của bạn, rồi để Tamas gợi ý loại hoa, tone màu và <span className="keep-together">khoảng ngân sách phù hợp.</span></p></div><div className="occasion-links">{[['Sinh nhật','sinh-nhat'],['Tốt nghiệp','tot-nghiep'],['Kỷ niệm','ky-niem'],['Tình yêu','tinh-yeu'],['Cưới','cuoi'],['Chúc mừng','chuc-mung']].map(([name,slug])=><Link key={slug} href={`/dip-tang/${slug}`}>{name}<Arrow/></Link>)}</div></section>
<section className="story"><div className="story-image"><Image src="/images/enhanced/01_Fresh-Flowers/tamas-fresh-pastel-bouquet-01.webp" alt="Bó hoa pastel được Tamas chuẩn bị" fill sizes="(max-width:720px) 100vw, 45vw"/></div><div><h2><span className="keep-together">Không chỉ là</span><br/><span className="keep-together">một bó hoa.</span></h2><p>Tại Tamas, một bó hoa bắt đầu bằng người nhận: họ thích điều gì, dịp hôm nay là gì, và bạn muốn họ cảm thấy thế nào khi mở món quà.</p><p>Chúng mình chuẩn bị hoa với sự chỉn chu của một món quà được gửi bằng <span className="keep-together">cả tấm lòng.</span></p><Link className="text-link" href="/ve-tamas">Câu chuyện của Tamas <Arrow/></Link></div></section>
<section className="custom"><div><p className="location">Tamas làm hoa theo câu chuyện của bạn</p><h2>Không tìm thấy mẫu bạn muốn?</h2><p>Hãy gửi Tamas người nhận, dịp tặng, tone màu và ngân sách. Shop sẽ tư vấn một thiết kế thật phù hợp.</p></div><a className="button button-paper" href={business.facebook} target="_blank" rel="noopener noreferrer">Đặt qua fanpage <Arrow/></a></section>
<section className="section instagram"><div className="section-heading"><div><h2>Một chút Tamas mỗi ngày.</h2><p>Khám phá thêm các mẫu hoa và câu chuyện từ shop.</p></div><a className="text-link" href={business.instagram} target="_blank" rel="noopener noreferrer">@tamas.flower <Arrow/></a></div><div className="insta-grid">{instagramImages.map((image,index)=><Image key={`${image.src}-${index}`} src={image.src} alt={image.alt} width={420} height={420}/>)}</div></section>
</PageShell>}
